"""Common controlled-attribution manifests, records, and admission guards."""

from worldspace.attribution.analysis import (
    admit_design_matrix_cohort,
    descriptive_contrast,
)
from worldspace.attribution.capabilities import (
    ca_capabilities,
    current_domain_capabilities,
    dungeon_capabilities,
    maze_capabilities,
    sphere_capabilities,
)
from worldspace.attribution.capture import (
    PROSPECTIVE_EVENT_FILENAME,
    ProspectiveEventCapture,
    archive_state_from_archive,
    read_prospective_events,
)
from worldspace.attribution.design import (
    CellMean,
    DescriptiveContrast,
    DesignCell,
    DesignMatrix,
    JobPlan,
    PairedDifference,
    PlannedContrast,
    ResourceProjection,
)
from worldspace.attribution.hashing import canonical_json_bytes, canonical_sha256
from worldspace.attribution.job_builder import (
    InitialArchiveRef,
    JobBuildContext,
    build_factorial_job_plan,
)
from worldspace.attribution.manifest import (
    SCHEMA_VERSION,
    AdapterCapabilities,
    ArmManifest,
    BudgetCaps,
    BudgetTreatment,
    ComponentSpec,
    EstimandSpec,
    RunManifest,
    RunManifestCore,
    StudyManifest,
    TreatmentVector,
    arm_treatment_hash,
    differing_treatment_axes,
    freeze_run_manifest,
    scientific_treatment_hash,
    study_manifest_hash,
)
from worldspace.attribution.records import (
    ArtifactManifest,
    ArchiveState,
    BudgetCheckpoint,
    BudgetCounters,
    ProposalEvent,
    RunSummary,
)
from worldspace.attribution.validation import (
    AdmissionIssue,
    AttributionAdmissionError,
    admit_analysis_cohort,
    require_study_capabilities,
    validate_study_capabilities,
)

__all__ = [
    "SCHEMA_VERSION",
    "AdapterCapabilities",
    "AdmissionIssue",
    "ArmManifest",
    "ArtifactManifest",
    "ArchiveState",
    "AttributionAdmissionError",
    "BudgetCaps",
    "BudgetCheckpoint",
    "BudgetCounters",
    "BudgetTreatment",
    "CellMean",
    "ComponentSpec",
    "DescriptiveContrast",
    "DesignCell",
    "DesignMatrix",
    "EstimandSpec",
    "InitialArchiveRef",
    "JobBuildContext",
    "JobPlan",
    "PairedDifference",
    "PlannedContrast",
    "PROSPECTIVE_EVENT_FILENAME",
    "ProposalEvent",
    "ProspectiveEventCapture",
    "ResourceProjection",
    "RunManifest",
    "RunManifestCore",
    "RunSummary",
    "StudyManifest",
    "TreatmentVector",
    "admit_analysis_cohort",
    "admit_design_matrix_cohort",
    "arm_treatment_hash",
    "archive_state_from_archive",
    "build_factorial_job_plan",
    "canonical_json_bytes",
    "canonical_sha256",
    "descriptive_contrast",
    "differing_treatment_axes",
    "freeze_run_manifest",
    "require_study_capabilities",
    "read_prospective_events",
    "scientific_treatment_hash",
    "study_manifest_hash",
    "validate_study_capabilities",
    "ca_capabilities",
    "current_domain_capabilities",
    "dungeon_capabilities",
    "maze_capabilities",
    "sphere_capabilities",
]
